execution:
  geth:
    name: ethereum/client-go
    version: v1.14.8
  besu:
    name: hyperledger/besu
    version: 24.8.0
  nethermind:
    name: nethermind/nethermind
    version: 1.28.0
  erigon:
    name: thorax/erigon
    version: v2.60.6
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v5.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.21.0
  teku:
    name: consensys/teku
    version: 24.8.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v5.1.0
  nimbus:
    name: statusim/nimbus-eth2
    version: multiarch-v24.8.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v5.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.21.0
  teku:
    name: consensys/teku
    version: 24.8.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v5.1.0
  nimbus:
    name: statusim/nimbus-validator-client
    version: multiarch-v24.8.0
optimism:
  optimism:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    version: v1.9.1