execution:
  geth:
    name: ethereum/client-go
    version: v1.16.8
  besu:
    name: hyperledger/besu
    version: 25.12.0
  nethermind:
    name: nethermind/nethermind
    version: 1.36.0
  erigon:
    name: erigontech/erigon
    version: v3.3.7
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v8.0.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.39.0
  teku:
    name: consensys/teku
    version: 25.12.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v7.1.2
  nimbus:
    name: statusim/nimbus-eth2
    version: v25.11.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v8.0.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.39.0
  teku:
    name: consensys/teku
    version: 25.12.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v7.1.2
  nimbus:
    name: statusim/nimbus-validator-client
    version: v25.11.0
distributed:
  charon:
    name: ghcr.io/obolnetwork/charon
    version: v7.1.2
optimism:
  opnode:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    version: v1.16.1
opexecution:
  opgeth:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    version: v1.101603.4
  opnethermind:
    name: nethermind/nethermind
    version: 1.35.2
  opreth:
    name: ghcr.io/paradigmxyz/op-reth
    version: v1.9.1
taiko:
  taikoclient:
    name: us-docker.pkg.dev/evmchain/images/taiko-client
    version: alethia-1.11.0
texecution:
  taikogeth:
    name: us-docker.pkg.dev/evmchain/images/taiko-geth
    version: v1.18.0
  taikonethermind:
    name: nethermind/nethermind
    version: 1.35.2
aztec:
  aztec:
    name: aztecprotocol/aztec
    version: 2.1.9
