execution:
  geth:
    name: ethereum/client-go
    version: v1.13.10
  besu:
    name: hyperledger/besu
    version: 24.1.0
  nethermind:
    name: nethermind/nethermind
    version: 1.25.3
  erigon:
    name: thorax/erigon
    version: v2.57.0
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.14.0
  teku:
    name: consensys/teku
    version: 24.1.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.2.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.14.0
  teku:
    name: consensys/teku
    version: 24.1.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.2.0
optimism:
  optimism:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    version: v1.3.2