execution:
  geth:
    name: ethereum/client-go
    version: v1.14.11
  besu:
    name: hyperledger/besu
    version: 24.10.0
  nethermind:
    name: nethermind/nethermind
    version: 1.29.1
  erigon:
    name: thorax/erigon
    version: v2.60.9
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v5.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.22.0
  teku:
    name: consensys/teku
    version: 24.10.3
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v5.1.2
  nimbus:
    name: statusim/nimbus-eth2
    version: multiarch-v24.10.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v5.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.22.0
  teku:
    name: consensys/teku
    version: 24.10.3
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v5.1.2
  nimbus:
    name: statusim/nimbus-validator-client
    version: multiarch-v24.10.0
optimism:
  opnode:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    version: v1.9.4
opexecution:
  opgeth:
    name: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    version: v1.101411.0
  opnethermind:
    name: nethermind/nethermind
    version: 1.29.1
  opreth:
    name: ghcr.io/paradigmxyz/op-reth
    version: v1.1.0
